# Generated by Django 4.0.3 on 2022-04-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_time'], name='feed_post_post_ti_705438_idx'),
        ),
    ]
