# Generated by Django 4.0.3 on 2022-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_post_time_post_feed_post_post_ti_705438_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
